version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update
      - apt-get install yarn
      - curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$HOME/.fnm" --skip-shell
      - export PATH=$HOME/.fnm:$PATH
      - eval "$(fnm env)"
      - fnm install
      - fnm use
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn lint
      - yarn type-check
      - yarn test-coverage
      - yarn build
      - yarn deploy
  post_build:
    commands:
      - yarn upload-coverage
