name: "Branch update"

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  RunLinters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

      - name: Check types
        run: yarn type-check
        shell: bash

      - name: Check linter rules
        run: yarn lint
        shell: bash
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

      - name: Run unit tests
        run: yarn test --coverage
        shell: bash

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  Deploy:
    runs-on: ubuntu-latest
    needs: [RunLinters, RunTests]
    steps:
      # TODO: Uncomment this when it's time to start deploying!
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     # These secrets are stored as repo-level secrets on Github.
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

      - name: Build
        run: yarn build
        shell: bash

      - name: Build Storybook
        run: yarn build-storybook
        shell: bash

      - name: Deploy
        run: yarn deploy --require-approval never
        shell: bash
