name: "Pull request"

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  RunLinters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

      - name: Check types
        run: yarn type-check
        shell: bash

      - name: Check linter rules
        run: yarn lint
        shell: bash
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

      - name: Run unit tests
        run: yarn test --coverage
        shell: bash

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
